# Generated by Django 6.0.2 on 2026-02-25 09:42

import django.db.models.deletion
import django_mongodb_backend.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_is_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='image_path',
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default='Ahmedabad', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='properties/videos/'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/extra/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='properties', to='api.amenity'),
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='property',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/main/'),
        ),
        migrations.AddField(
            model_name='property',
            name='appliances',
            field=models.ManyToManyField(blank=True, related_name='properties', to='api.appliance'),
        ),
    ]
