# Generated by Django 6.0.2 on 2026-02-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_appliance_remove_property_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='beds',
            field=models.IntegerField(default=1),
        ),
    ]
