# Generated by Django 6.0.2 on 2026-02-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_room_beds'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='available_beds',
            field=models.IntegerField(default=1),
        ),
    ]
