# Generated by Django 6.0.2 on 2026-03-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_otp_booking_amount_booking_customer_age_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
        migrations.AddField(
            model_name='user',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
