# Generated by Django 5.2.12 on 2026-03-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_review_user_alter_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_verified',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/'),
        ),
    ]
