# Generated by Django 5.2.12 on 2026-03-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20240307_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='face_photo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
