# Generated by Django 5.2.15 on 2026-07-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_user_business_name_user_face_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='total_beds',
            field=models.IntegerField(default=20),
        ),
    ]
