# Generated by Django 5.2.15 on 2026-08-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_created_at_to_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(db_index=True, default='Ahmedabad', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='gender',
            field=models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Co-ed', 'Co-ed')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_verified',
            field=models.BooleanField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='rating',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('Hostel', 'Hostel'), ('PG', 'PG')], db_index=True, max_length=20),
        ),
    ]
