services:
  - type: web
    name: bed-buddy-backend
    env: python
    plan: free
    buildCommand: "pip install -r backend/requirements.txt && python backend/manage.py collectstatic --noinput"
    startCommand: "gunicorn --chdir backend nestnode_backend.wsgi --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.2
      - key: DJANGO_SETTINGS_MODULE
        value: nestnode_backend.settings
      - key: DEBUG
        value: false
      - key: SECURE_SSL_REDIRECT
        value: true
      - key: RENDER
        value: true
