[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn nestnode_backend.wsgi --bind 0.0.0.0:$PORT"
```

Your file probably looks like this (wrong ❌):
```
```toml
[phases.setup]
...
```
```

It should look like this (correct ✅):
```
[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn nestnode_backend.wsgi --bind 0.0.0.0:$PORT"